# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  default_velocity_scaling_factor: 0.1
  default_acceleration_scaling_factor: 0.1
  velocity_scaling_factor: 0.1
  acceleration_scaling_factor: 0.1
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.6
    has_acceleration_limits: true
    max_acceleration: 5.2
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.6
    has_acceleration_limits: true
    max_acceleration: 5.2
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 3.8
  joint_4:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 3.8
  joint_5:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 3.8
  joint_6:
    has_velocity_limits: true
    max_velocity: 2.2
    has_acceleration_limits: true
    max_acceleration: 4.4
  joint_7:
    has_velocity_limits: true
    max_velocity: 2.2
    has_acceleration_limits: true
    max_acceleration: 4.4

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1
velocity_scaling_factor: 0.1
acceleration_scaling_factor: 0.1